### ISSUE TITLE
pahole.py doesn't seem to work

### ISSUE THREAD

**Issue by 1120161891** [seclab-ucr/KOOBE#5]

**Comment by Niebelungen-D** [comment]
Hello I have the same problem. An error always occurs in the file.  Do you have any solution please?

```text
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    Commands[args.cmd].run(args)
  File "/home/niebelungen/KOOBE/aeg-analysis/aeg/commands/pahole.py", line 646, in run
    pahole.analyzeType()
  File "/home/niebelungen/KOOBE/aeg-analysis/aeg/commands/pahole.py", line 414, in analyzeType
    struct = Struct(content, self)
  File "/home/niebelungen/KOOBE/aeg-analysis/aeg/commands/pahole.py", line 326, in __init__
    self._fields.append(Field(line, self._pahole))
  File "/home/niebelungen/KOOBE/aeg-analysis/aeg/commands/pahole.py", line 152, in __init__
    define = m.group(1).strip()
AttributeError: 'NoneType' object has no attribute 'group'
```

I have tried to modify the file, but it does not work. Other error will occur. 
```python
+                if re.search('(.+)/\*\s(.+)\s+\*/', line.strip()) != None:
                    self._fields.append(Field(line, self._pahole))
```

**Comment by Albocoder** [comment]
#4 fixed it for pahole `1.21` just pull that

**Comment by heChosen** [comment]
Can anyone fully reproduce this study? I encountered some difficulties during the construction process.It will get stuck in `touch /home/hara/KOOBE/s2e/images/.stamps/linux-4.9.3-x86_64`
